# Generated by Django 4.1.1 on 2023-04-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_likes_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
