# Generated by Django 4.1.1 on 2023-04-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_like_likes_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
