# Generated by Django 4.1.1 on 2023-05-01 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_by',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
