# Generated by Django 4.1.1 on 2023-03-13 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_winner',
            name='auction_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction_listing'),
        ),
    ]
