# Generated by Django 4.1.1 on 2023-03-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_winner_auction_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
