# Generated by Django 4.2.2 on 2024-01-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddatajson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
